# Каталог космических объектов с расстояниями в световых годах.
# distance_ly = 0  для объектов Солнечной системы (их расстояние указано в distance_note).
# Данные основаны на актуальных астрономических каталогах (Hipparcos, NED, SIMBAD).

CATALOG = [

    # ══════════════════════════════
    #  СОЛНЕЧНАЯ СИСТЕМА
    # ══════════════════════════════
    {
        'id': 'sun',
        'catalog_id': '—',
        'name': 'Sun',              'name_ru': 'Солнце',
        'type': 'solar',            'type_ru': 'Звезда (Солнце)',
        'constellation': '—',
        'distance_ly': 0.0000158,
        'distance_note': '8 световых минут',
        'distance_note_en': '8 light-minutes',
        'magnitude': -26.74,
        'ra': '—', 'dec': '—',
        'description_ru': 'Звезда в центре Солнечной системы. Спектральный класс G2V. Диаметр — 1 392 700 км.',
        'description_en': 'Star at the center of our Solar System. Spectral type G2V. Diameter — 1,392,700 km.',
    },
    {
        'id': 'mercury', 'catalog_id': '—',
        'name': 'Mercury', 'name_ru': 'Меркурий',
        'type': 'solar',   'type_ru': 'Планета',
        'constellation': '—',
        'distance_ly': 0.0000063,
        'distance_note': '~3.2 световых минуты (среднее)', 'distance_note_en': '~3.2 light-minutes (avg)',
        'magnitude': -2.6, 'ra': '—', 'dec': '—',
        'description_ru': 'Ближайшая к Солнцу планета. Период обращения — 88 земных суток.',
        'description_en': 'Closest planet to the Sun. Orbital period — 88 Earth days.',
    },
    {
        'id': 'venus', 'catalog_id': '—',
        'name': 'Venus', 'name_ru': 'Венера',
        'type': 'solar',  'type_ru': 'Планета',
        'constellation': '—',
        'distance_ly': 0.0000121,
        'distance_note': '~6 световых минут (среднее)', 'distance_note_en': '~6 light-minutes (avg)',
        'magnitude': -4.6, 'ra': '—', 'dec': '—',
        'description_ru': 'Самая яркая планета на небе. Температура поверхности +465 °C.',
        'description_en': 'Brightest planet in the sky. Surface temperature +465 °C.',
    },
    {
        'id': 'mars', 'catalog_id': '—',
        'name': 'Mars', 'name_ru': 'Марс',
        'type': 'solar', 'type_ru': 'Планета',
        'constellation': '—',
        'distance_ly': 0.0000242,
        'distance_note': '~12.5 световых минут (среднее)', 'distance_note_en': '~12.5 light-minutes (avg)',
        'magnitude': -2.94, 'ra': '—', 'dec': '—',
        'description_ru': 'Красная планета. Имеет два спутника: Фобос и Деймос.',
        'description_en': 'The Red Planet. Has two moons: Phobos and Deimos.',
    },
    {
        'id': 'jupiter', 'catalog_id': '—',
        'name': 'Jupiter', 'name_ru': 'Юпитер',
        'type': 'solar', 'type_ru': 'Планета',
        'constellation': '—',
        'distance_ly': 0.0000826,
        'distance_note': '~43 световые минуты (среднее)', 'distance_note_en': '~43 light-minutes (avg)',
        'magnitude': -2.94, 'ra': '—', 'dec': '—',
        'description_ru': 'Крупнейшая планета Солнечной системы. Масса — 318 земных масс. 95 известных спутников.',
        'description_en': 'Largest planet in the Solar System. Mass — 318 Earth masses. 95 known moons.',
    },
    {
        'id': 'saturn', 'catalog_id': '—',
        'name': 'Saturn', 'name_ru': 'Сатурн',
        'type': 'solar', 'type_ru': 'Планета',
        'constellation': '—',
        'distance_ly': 0.000152,
        'distance_note': '~1.3 световых часа (среднее)', 'distance_note_en': '~1.3 light-hours (avg)',
        'magnitude': 0.46, 'ra': '—', 'dec': '—',
        'description_ru': 'Газовый гигант с кольцами из льда и пыли. Плотность ниже, чем у воды.',
        'description_en': 'Gas giant famous for its ice and dust rings. Density lower than water.',
    },
    {
        'id': 'uranus', 'catalog_id': '—',
        'name': 'Uranus', 'name_ru': 'Уран',
        'type': 'solar', 'type_ru': 'Планета',
        'constellation': '—',
        'distance_ly': 0.000306,
        'distance_note': '~2.7 световых часа (среднее)', 'distance_note_en': '~2.7 light-hours (avg)',
        'magnitude': 5.68, 'ra': '—', 'dec': '—',
        'description_ru': 'Ледяной гигант. Ось вращения наклонена почти на 98° — планета вращается «на боку».',
        'description_en': 'Ice giant. Rotation axis tilted ~98° — the planet rolls on its side.',
    },
    {
        'id': 'neptune', 'catalog_id': '—',
        'name': 'Neptune', 'name_ru': 'Нептун',
        'type': 'solar', 'type_ru': 'Планета',
        'constellation': '—',
        'distance_ly': 0.000479,
        'distance_note': '~4.2 световых часа (среднее)', 'distance_note_en': '~4.2 light-hours (avg)',
        'magnitude': 7.85, 'ra': '—', 'dec': '—',
        'description_ru': 'Самая дальняя планета Солнечной системы. Ветры до 2100 км/ч.',
        'description_en': 'Farthest planet in the Solar System. Winds up to 2,100 km/h.',
    },

    # ══════════════════════════════
    #  ЗВЁЗДЫ
    # ══════════════════════════════
    {
        'id': 'proxima_cen', 'catalog_id': 'Proxima Cen',
        'name': 'Proxima Centauri', 'name_ru': 'Проксима Центавра',
        'type': 'star', 'type_ru': 'Красный карлик',
        'constellation': 'Centaurus',
        'distance_ly': 4.24,
        'distance_note': '4.24 световых года', 'distance_note_en': '4.24 light-years',
        'magnitude': 11.13, 'ra': '14h 29m 43s', 'dec': '−62° 40′ 46″',
        'description_ru': 'Ближайшая к Солнцу звезда. Красный карлик. Имеет планету Проксима b в зоне обитаемости.',
        'description_en': 'Nearest star to the Sun. Red dwarf. Has a planet Proxima b in the habitable zone.',
    },
    {
        'id': 'alpha_cen', 'catalog_id': 'α Cen',
        'name': 'Alpha Centauri', 'name_ru': 'Альфа Центавра',
        'type': 'star', 'type_ru': 'Двойная звезда',
        'constellation': 'Centaurus',
        'distance_ly': 4.37,
        'distance_note': '4.37 световых года', 'distance_note_en': '4.37 light-years',
        'magnitude': -0.27, 'ra': '14h 39m 36s', 'dec': '−60° 50′ 02″',
        'description_ru': 'Тройная звёздная система. Ярчайшая звезда южного полушария.',
        'description_en': 'Triple star system. Brightest star in the southern hemisphere.',
    },
    {
        'id': 'barnards', 'catalog_id': "Barnard's Star",
        'name': "Barnard's Star", 'name_ru': 'Звезда Барнарда',
        'type': 'star', 'type_ru': 'Красный карлик',
        'constellation': 'Ophiuchus',
        'distance_ly': 5.96,
        'distance_note': '5.96 световых года', 'distance_note_en': '5.96 light-years',
        'magnitude': 9.54, 'ra': '17h 57m 49s', 'dec': '+04° 41′ 36″',
        'description_ru': 'Имеет наибольшее собственное движение среди всех звёзд — 10.36″ в год.',
        'description_en': 'Has the largest proper motion of any known star — 10.36″ per year.',
    },
    {
        'id': 'sirius', 'catalog_id': 'α CMa',
        'name': 'Sirius', 'name_ru': 'Сириус',
        'type': 'star', 'type_ru': 'Белая звезда главной последовательности',
        'constellation': 'Canis Major',
        'distance_ly': 8.6,
        'distance_note': '8.6 световых года', 'distance_note_en': '8.6 light-years',
        'magnitude': -1.46, 'ra': '06h 45m 09s', 'dec': '−16° 42′ 58″',
        'description_ru': 'Ярчайшая звезда ночного неба. Двойная система — Сириус A и белый карлик Сириус B.',
        'description_en': 'Brightest star in the night sky. Binary system — Sirius A and white dwarf Sirius B.',
    },
    {
        'id': 'vega', 'catalog_id': 'α Lyr',
        'name': 'Vega', 'name_ru': 'Вега',
        'type': 'star', 'type_ru': 'Белая звезда главной последовательности',
        'constellation': 'Lyra',
        'distance_ly': 25.0,
        'distance_note': '25 световых лет', 'distance_note_en': '25 light-years',
        'magnitude': 0.03, 'ra': '18h 36m 56s', 'dec': '+38° 47′ 01″',
        'description_ru': 'Одна из вершин летнего треугольника. Эталонная звезда нулевой звёздной величины.',
        'description_en': 'One vertex of the Summer Triangle. Reference star for the zero magnitude scale.',
    },
    {
        'id': 'polaris', 'catalog_id': 'α UMi',
        'name': 'Polaris', 'name_ru': 'Полярная звезда',
        'type': 'star', 'type_ru': 'Цефеида (сверхгигант)',
        'constellation': 'Ursa Minor',
        'distance_ly': 433.0,
        'distance_note': '433 световых года', 'distance_note_en': '433 light-years',
        'magnitude': 1.98, 'ra': '02h 31m 49s', 'dec': '+89° 15′ 51″',
        'description_ru': 'Находится менее чем в 1° от Северного полюса мира. Тройная звёздная система.',
        'description_en': 'Located less than 1° from the north celestial pole. Triple star system.',
    },
    {
        'id': 'betelgeuse', 'catalog_id': 'α Ori',
        'name': 'Betelgeuse', 'name_ru': 'Бетельгейзе',
        'type': 'star', 'type_ru': 'Красный сверхгигант',
        'constellation': 'Orion',
        'distance_ly': 700.0,
        'distance_note': '~700 световых лет', 'distance_note_en': '~700 light-years',
        'magnitude': 0.5, 'ra': '05h 55m 10s', 'dec': '+07° 24′ 25″',
        'description_ru': 'Красный сверхгигант. Если бы находился на месте Солнца — поглотил бы орбиту Юпитера. Кандидат в сверхновые.',
        'description_en': 'Red supergiant. If placed at the Sun, it would engulf Jupiter\'s orbit. Supernova candidate.',
    },
    {
        'id': 'rigel', 'catalog_id': 'β Ori',
        'name': 'Rigel', 'name_ru': 'Ригель',
        'type': 'star', 'type_ru': 'Голубой сверхгигант',
        'constellation': 'Orion',
        'distance_ly': 860.0,
        'distance_note': '~860 световых лет', 'distance_note_en': '~860 light-years',
        'magnitude': 0.13, 'ra': '05h 14m 32s', 'dec': '−08° 12′ 06″',
        'description_ru': 'Ярчайший голубой сверхгигант. Светимость в 120 000 раз превышает солнечную.',
        'description_en': 'Brightest blue supergiant. Luminosity 120,000 times that of the Sun.',
    },
    {
        'id': 'antares', 'catalog_id': 'α Sco',
        'name': 'Antares', 'name_ru': 'Антарес',
        'type': 'star', 'type_ru': 'Красный сверхгигант',
        'constellation': 'Scorpius',
        'distance_ly': 550.0,
        'distance_note': '~550 световых лет', 'distance_note_en': '~550 light-years',
        'magnitude': 1.09, 'ra': '16h 29m 24s', 'dec': '−26° 25′ 55″',
        'description_ru': 'Сердце Скорпиона. Диаметр — 700 диаметров Солнца. Кандидат в сверхновые.',
        'description_en': 'Heart of Scorpius. Diameter — 700 solar diameters. Supernova candidate.',
    },
    {
        'id': 'deneb', 'catalog_id': 'α Cyg',
        'name': 'Deneb', 'name_ru': 'Денеб',
        'type': 'star', 'type_ru': 'Белый сверхгигант',
        'constellation': 'Cygnus',
        'distance_ly': 2615.0,
        'distance_note': '~2 615 световых лет', 'distance_note_en': '~2,615 light-years',
        'magnitude': 1.25, 'ra': '20h 41m 26s', 'dec': '+45° 16′ 49″',
        'description_ru': 'Одна из самых далёких ярких звёзд. Входит в летний треугольник. Светимость в 200 000 раз больше солнечной.',
        'description_en': 'One of the most distant bright stars. Part of the Summer Triangle. Luminosity 200,000× the Sun.',
    },
    {
        'id': 'aldebaran', 'catalog_id': 'α Tau',
        'name': 'Aldebaran', 'name_ru': 'Альдебаран',
        'type': 'star', 'type_ru': 'Красный гигант',
        'constellation': 'Taurus',
        'distance_ly': 65.0,
        'distance_note': '65 световых лет', 'distance_note_en': '65 light-years',
        'magnitude': 0.86, 'ra': '04h 35m 55s', 'dec': '+16° 30′ 33″',
        'description_ru': 'Красный гигант, «глаз» Тельца. Диаметр — 44 диаметра Солнца.',
        'description_en': 'Red giant, the "eye" of Taurus. Diameter — 44 solar diameters.',
    },

    # ══════════════════════════════
    #  ТУМАННОСТИ
    # ══════════════════════════════
    {
        'id': 'm1', 'catalog_id': 'M1 / NGC 1952',
        'name': 'Crab Nebula', 'name_ru': 'Крабовидная туманность',
        'type': 'nebula', 'type_ru': 'Остаток сверхновой',
        'constellation': 'Taurus',
        'distance_ly': 6500,
        'distance_note': '6 500 световых лет', 'distance_note_en': '6,500 light-years',
        'magnitude': 8.4, 'ra': '05h 34m 32s', 'dec': '+22° 00′ 52″',
        'description_ru': 'Остаток взрыва сверхновой SN 1054, зафиксированного в 1054 г. В центре — пульсар.',
        'description_en': 'Remnant of supernova SN 1054, recorded in 1054 AD. A pulsar lies at the center.',
    },
    {
        'id': 'm8', 'catalog_id': 'M8 / NGC 6523',
        'name': 'Lagoon Nebula', 'name_ru': 'Лагуна',
        'type': 'nebula', 'type_ru': 'Эмиссионная туманность',
        'constellation': 'Sagittarius',
        'distance_ly': 4100,
        'distance_note': '4 100 световых лет', 'distance_note_en': '4,100 light-years',
        'magnitude': 6.0, 'ra': '18h 03m 37s', 'dec': '−24° 23′ 12″',
        'description_ru': 'Крупная эмиссионная туманность. Видна невооружённым глазом в тёмную ночь.',
        'description_en': 'Large emission nebula visible to the naked eye on a dark night.',
    },
    {
        'id': 'm16', 'catalog_id': 'M16 / NGC 6611',
        'name': 'Eagle Nebula', 'name_ru': 'Орёл',
        'type': 'nebula', 'type_ru': 'Эмиссионная туманность',
        'constellation': 'Serpens',
        'distance_ly': 7000,
        'distance_note': '7 000 световых лет', 'distance_note_en': '7,000 light-years',
        'magnitude': 6.4, 'ra': '18h 18m 48s', 'dec': '−13° 49′ 00″',
        'description_ru': 'Содержит знаменитые «Столпы Творения» — плотные колонны газа, снятые телескопом Хаббл в 1995 г.',
        'description_en': 'Contains the famous "Pillars of Creation" — dense gas columns photographed by Hubble in 1995.',
    },
    {
        'id': 'm20', 'catalog_id': 'M20 / NGC 6514',
        'name': 'Trifid Nebula', 'name_ru': 'Трёхдольная туманность',
        'type': 'nebula', 'type_ru': 'Эмиссионная/рефлективная туманность',
        'constellation': 'Sagittarius',
        'distance_ly': 5200,
        'distance_note': '5 200 световых лет', 'distance_note_en': '5,200 light-years',
        'magnitude': 6.3, 'ra': '18h 02m 23s', 'dec': '−23° 01′ 48″',
        'description_ru': 'Трёхдольная туманность разделена тёмными пылевыми полосами.',
        'description_en': 'Divided into three lobes by dark dust lanes.',
    },
    {
        'id': 'm27', 'catalog_id': 'M27 / NGC 6853',
        'name': 'Dumbbell Nebula', 'name_ru': 'Гантель',
        'type': 'nebula', 'type_ru': 'Планетарная туманность',
        'constellation': 'Vulpecula',
        'distance_ly': 1360,
        'distance_note': '1 360 световых лет', 'distance_note_en': '1,360 light-years',
        'magnitude': 7.5, 'ra': '19h 59m 36s', 'dec': '+22° 43′ 16″',
        'description_ru': 'Первая обнаруженная планетарная туманность (Мессье, 1764). Хорошо видна в бинокль.',
        'description_en': 'First planetary nebula to be discovered (Messier, 1764). Visible in binoculars.',
    },
    {
        'id': 'm42', 'catalog_id': 'M42 / NGC 1976',
        'name': 'Orion Nebula', 'name_ru': 'Туманность Ориона',
        'type': 'nebula', 'type_ru': 'Диффузная туманность',
        'constellation': 'Orion',
        'distance_ly': 1344,
        'distance_note': '1 344 световых года', 'distance_note_en': '1,344 light-years',
        'magnitude': 4.0, 'ra': '05h 35m 17s', 'dec': '−05° 23′ 28″',
        'description_ru': 'Ближайший регион активного звездообразования. Видна невооружённым глазом.',
        'description_en': 'Nearest active star-forming region. Visible to the naked eye.',
    },
    {
        'id': 'm57', 'catalog_id': 'M57 / NGC 6720',
        'name': 'Ring Nebula', 'name_ru': 'Кольцо',
        'type': 'nebula', 'type_ru': 'Планетарная туманность',
        'constellation': 'Lyra',
        'distance_ly': 2300,
        'distance_note': '2 300 световых лет', 'distance_note_en': '2,300 light-years',
        'magnitude': 8.8, 'ra': '18h 53m 35s', 'dec': '+33° 01′ 45″',
        'description_ru': 'Классическая планетарная туманность — оболочка, сброшенная умирающей звездой.',
        'description_en': 'Classic planetary nebula — shell ejected by a dying star.',
    },
    {
        'id': 'helix', 'catalog_id': 'NGC 7293',
        'name': 'Helix Nebula', 'name_ru': 'Улитка',
        'type': 'nebula', 'type_ru': 'Планетарная туманность',
        'constellation': 'Aquarius',
        'distance_ly': 650,
        'distance_note': '650 световых лет', 'distance_note_en': '650 light-years',
        'magnitude': 7.3, 'ra': '22h 29m 38s', 'dec': '−20° 50′ 14″',
        'description_ru': 'Ближайшая к нам крупная планетарная туманность. Диаметр — 3 световых года.',
        'description_en': 'Nearest large planetary nebula to Earth. Diameter — 3 light-years.',
    },
    {
        'id': 'horsehead', 'catalog_id': 'IC 434 / B 33',
        'name': 'Horsehead Nebula', 'name_ru': 'Конская голова',
        'type': 'nebula', 'type_ru': 'Тёмная туманность',
        'constellation': 'Orion',
        'distance_ly': 1500,
        'distance_note': '1 500 световых лет', 'distance_note_en': '1,500 light-years',
        'magnitude': None, 'ra': '05h 40m 59s', 'dec': '−02° 27′ 30″',
        'description_ru': 'Тёмная туманность на фоне более яркой IC 434. Один из символов астрофотографии.',
        'description_en': 'Dark nebula silhouetted against the brighter IC 434. An icon of astrophotography.',
    },
    {
        'id': 'catseye', 'catalog_id': 'NGC 6543',
        'name': "Cat's Eye Nebula", 'name_ru': 'Кошачий глаз',
        'type': 'nebula', 'type_ru': 'Планетарная туманность',
        'constellation': 'Draco',
        'distance_ly': 3300,
        'distance_note': '3 300 световых лет', 'distance_note_en': '3,300 light-years',
        'magnitude': 8.1, 'ra': '17h 58m 33s', 'dec': '+66° 37′ 59″',
        'description_ru': 'Одна из самых сложных планетарных туманностей. Открыта Уильямом Хёрсхелем в 1786 г.',
        'description_en': 'One of the most complex planetary nebulae. Discovered by William Herschel in 1786.',
    },
    {
        'id': 'california', 'catalog_id': 'NGC 1499',
        'name': 'California Nebula', 'name_ru': 'Туманность Калифорния',
        'type': 'nebula', 'type_ru': 'Эмиссионная туманность',
        'constellation': 'Perseus',
        'distance_ly': 1000,
        'distance_note': '1 000 световых лет', 'distance_note_en': '1,000 light-years',
        'magnitude': 6.0, 'ra': '04h 03m 18s', 'dec': '+36° 25′ 18″',
        'description_ru': 'Протяжённая эмиссионная туманность, по форме напоминающая штат Калифорния.',
        'description_en': 'Extended emission nebula shaped like the state of California.',
    },
    {
        'id': 'rosette', 'catalog_id': 'NGC 2244',
        'name': 'Rosette Nebula', 'name_ru': 'Туманность Розетта',
        'type': 'nebula', 'type_ru': 'Эмиссионная туманность',
        'constellation': 'Monoceros',
        'distance_ly': 5200,
        'distance_note': '5 200 световых лет', 'distance_note_en': '5,200 light-years',
        'magnitude': 9.0, 'ra': '06h 33m 45s', 'dec': '+04° 59′ 54″',
        'description_ru': 'Огромная круглая туманность диаметром ~130 световых лет.',
        'description_en': 'Huge circular nebula ~130 light-years in diameter.',
    },

    # ══════════════════════════════
    #  ЗВЁЗДНЫЕ СКОПЛЕНИЯ
    # ══════════════════════════════
    {
        'id': 'm45', 'catalog_id': 'M45',
        'name': 'Pleiades', 'name_ru': 'Плеяды',
        'type': 'star_cluster', 'type_ru': 'Рассеянное скопление',
        'constellation': 'Taurus',
        'distance_ly': 444,
        'distance_note': '444 световых года', 'distance_note_en': '444 light-years',
        'magnitude': 1.6, 'ra': '03h 47m 24s', 'dec': '+24° 07′ 00″',
        'description_ru': 'Семь сестёр. Видны невооружённым глазом. Скопление молодых горячих звёзд (возраст ~115 млн лет).',
        'description_en': 'The Seven Sisters. Visible to the naked eye. Young hot star cluster (~115 million years old).',
    },
    {
        'id': 'hyades', 'catalog_id': 'Mel 25',
        'name': 'Hyades', 'name_ru': 'Гиады',
        'type': 'star_cluster', 'type_ru': 'Рассеянное скопление',
        'constellation': 'Taurus',
        'distance_ly': 153,
        'distance_note': '153 световых года', 'distance_note_en': '153 light-years',
        'magnitude': 0.5, 'ra': '04h 27m 00s', 'dec': '+15° 52′ 00″',
        'description_ru': 'Ближайшее к Земле звёздное скопление. Опорная точка для измерения космических расстояний.',
        'description_en': 'Nearest open cluster to Earth. Key reference point for measuring cosmic distances.',
    },
    {
        'id': 'm13', 'catalog_id': 'M13 / NGC 6205',
        'name': 'Hercules Cluster', 'name_ru': 'Шаровое скопление Геркулеса',
        'type': 'star_cluster', 'type_ru': 'Шаровое скопление',
        'constellation': 'Hercules',
        'distance_ly': 25100,
        'distance_note': '25 100 световых лет', 'distance_note_en': '25,100 light-years',
        'magnitude': 5.8, 'ra': '16h 41m 41s', 'dec': '+36° 27′ 37″',
        'description_ru': 'Крупнейшее шаровое скопление северного неба. Содержит ~300 000 звёзд.',
        'description_en': 'Largest globular cluster in the northern sky. Contains ~300,000 stars.',
    },
    {
        'id': 'omega_cen', 'catalog_id': 'NGC 5139 / ω Cen',
        'name': 'Omega Centauri', 'name_ru': 'Омега Центавра',
        'type': 'star_cluster', 'type_ru': 'Шаровое скопление',
        'constellation': 'Centaurus',
        'distance_ly': 17090,
        'distance_note': '17 090 световых лет', 'distance_note_en': '17,090 light-years',
        'magnitude': 3.9, 'ra': '13h 26m 47s', 'dec': '−47° 28′ 46″',
        'description_ru': 'Крупнейшее шаровое скопление в Галактике Млечный Путь. Содержит >10 млн звёзд. Возможно — ядро поглощённой карликовой галактики.',
        'description_en': 'Largest globular cluster in the Milky Way. Contains >10 million stars. Possibly the nucleus of an absorbed dwarf galaxy.',
    },
    {
        'id': 'm44', 'catalog_id': 'M44 / NGC 2632',
        'name': 'Beehive Cluster', 'name_ru': 'Ясли',
        'type': 'star_cluster', 'type_ru': 'Рассеянное скопление',
        'constellation': 'Cancer',
        'distance_ly': 577,
        'distance_note': '577 световых лет', 'distance_note_en': '577 light-years',
        'magnitude': 3.7, 'ra': '08h 40m 24s', 'dec': '+19° 40′ 00″',
        'description_ru': 'Одно из ближайших рассеянных скоплений. Известно с древности.',
        'description_en': 'One of the nearest open clusters. Known since antiquity.',
    },
    {
        'id': 'm11', 'catalog_id': 'M11 / NGC 6705',
        'name': 'Wild Duck Cluster', 'name_ru': 'Дикая Утка',
        'type': 'star_cluster', 'type_ru': 'Рассеянное скопление',
        'constellation': 'Scutum',
        'distance_ly': 6200,
        'distance_note': '6 200 световых лет', 'distance_note_en': '6,200 light-years',
        'magnitude': 5.8, 'ra': '18h 51m 05s', 'dec': '−06° 16′ 00″',
        'description_ru': 'Одно из богатейших рассеянных скоплений. Содержит около 2900 звёзд.',
        'description_en': 'One of the richest open clusters. Contains about 2,900 stars.',
    },
    {
        'id': 'double_cluster', 'catalog_id': 'NGC 869 / NGC 884',
        'name': 'Double Cluster', 'name_ru': 'Двойное скопление в Персее',
        'type': 'star_cluster', 'type_ru': 'Двойное рассеянное скопление',
        'constellation': 'Perseus',
        'distance_ly': 7500,
        'distance_note': '7 500 световых лет', 'distance_note_en': '7,500 light-years',
        'magnitude': 4.3, 'ra': '02h 20m 00s', 'dec': '+57° 08′ 00″',
        'description_ru': 'Два молодых скопления, видимые рядом на небе. Фотогеничный объект для широкопольных снимков.',
        'description_en': 'Two young clusters appearing close together in the sky. Photogenic target for wide-field imaging.',
    },

    # ══════════════════════════════
    #  ГАЛАКТИКИ
    # ══════════════════════════════
    {
        'id': 'lmc', 'catalog_id': 'LMC',
        'name': 'Large Magellanic Cloud', 'name_ru': 'Большое Магелланово Облако',
        'type': 'galaxy', 'type_ru': 'Иррегулярная галактика',
        'constellation': 'Dorado / Mensa',
        'distance_ly': 163000,
        'distance_note': '163 000 световых лет', 'distance_note_en': '163,000 light-years',
        'magnitude': 0.9, 'ra': '05h 23m 34s', 'dec': '−69° 45′ 22″',
        'description_ru': 'Галактика-спутник Млечного Пути. Видна невооружённым глазом из южного полушария.',
        'description_en': 'Satellite galaxy of the Milky Way. Visible to the naked eye from the southern hemisphere.',
    },
    {
        'id': 'smc', 'catalog_id': 'SMC',
        'name': 'Small Magellanic Cloud', 'name_ru': 'Малое Магелланово Облако',
        'type': 'galaxy', 'type_ru': 'Иррегулярная галактика',
        'constellation': 'Tucana',
        'distance_ly': 200000,
        'distance_note': '200 000 световых лет', 'distance_note_en': '200,000 light-years',
        'magnitude': 2.7, 'ra': '00h 52m 38s', 'dec': '−72° 48′ 01″',
        'description_ru': 'Меньший спутник Млечного Пути. Сыграла ключевую роль в открытии переменных звёзд-цефеид.',
        'description_en': 'Smaller satellite of the Milky Way. Key role in the discovery of Cepheid variable stars.',
    },
    {
        'id': 'm31', 'catalog_id': 'M31 / NGC 224',
        'name': 'Andromeda Galaxy', 'name_ru': 'Галактика Андромеды',
        'type': 'galaxy', 'type_ru': 'Спиральная галактика',
        'constellation': 'Andromeda',
        'distance_ly': 2537000,
        'distance_note': '2.54 млн световых лет', 'distance_note_en': '2.54 million light-years',
        'magnitude': 3.44, 'ra': '00h 42m 44s', 'dec': '+41° 16′ 09″',
        'description_ru': 'Ближайшая крупная галактика к Млечному Пути. Содержит ~1 триллион звёзд. Через ~4.5 млрд лет столкнётся с нашей галактикой.',
        'description_en': 'Nearest major galaxy to the Milky Way. Contains ~1 trillion stars. Will merge with the Milky Way in ~4.5 billion years.',
    },
    {
        'id': 'm33', 'catalog_id': 'M33 / NGC 598',
        'name': 'Triangulum Galaxy', 'name_ru': 'Галактика Треугольника',
        'type': 'galaxy', 'type_ru': 'Спиральная галактика',
        'constellation': 'Triangulum',
        'distance_ly': 2730000,
        'distance_note': '2.73 млн световых лет', 'distance_note_en': '2.73 million light-years',
        'magnitude': 5.72, 'ra': '01h 33m 51s', 'dec': '+30° 39′ 37″',
        'description_ru': 'Третья по размеру галактика Местной группы. Содержит ~40 млрд звёзд.',
        'description_en': 'Third-largest galaxy in the Local Group. Contains ~40 billion stars.',
    },
    {
        'id': 'm51', 'catalog_id': 'M51 / NGC 5194',
        'name': 'Whirlpool Galaxy', 'name_ru': 'Водоворот',
        'type': 'galaxy', 'type_ru': 'Спиральная галактика',
        'constellation': 'Canes Venatici',
        'distance_ly': 23000000,
        'distance_note': '23 млн световых лет', 'distance_note_en': '23 million light-years',
        'magnitude': 8.4, 'ra': '13h 29m 53s', 'dec': '+47° 11′ 43″',
        'description_ru': 'Первая галактика, в которой обнаружена спиральная структура (Лорд Росс, 1845). Взаимодействует со спутником NGC 5195.',
        'description_en': 'First galaxy where a spiral structure was observed (Lord Rosse, 1845). Interacting with companion NGC 5195.',
    },
    {
        'id': 'm81', 'catalog_id': 'M81 / NGC 3031',
        'name': "Bode's Galaxy", 'name_ru': 'Галактика Боде',
        'type': 'galaxy', 'type_ru': 'Спиральная галактика',
        'constellation': 'Ursa Major',
        'distance_ly': 11800000,
        'distance_note': '11.8 млн световых лет', 'distance_note_en': '11.8 million light-years',
        'magnitude': 6.94, 'ra': '09h 55m 33s', 'dec': '+69° 03′ 55″',
        'description_ru': 'Яркая спиральная галактика. Взаимодействует с соседними M82 и NGC 3077.',
        'description_en': 'Bright spiral galaxy. Interacting with neighbors M82 and NGC 3077.',
    },
    {
        'id': 'm82', 'catalog_id': 'M82 / NGC 3034',
        'name': 'Cigar Galaxy', 'name_ru': 'Сигара',
        'type': 'galaxy', 'type_ru': 'Иррегулярная галактика',
        'constellation': 'Ursa Major',
        'distance_ly': 12000000,
        'distance_note': '12 млн световых лет', 'distance_note_en': '12 million light-years',
        'magnitude': 8.41, 'ra': '09h 55m 52s', 'dec': '+69° 40′ 47″',
        'description_ru': 'Галактика с интенсивным звездообразованием. Из ядра вырывается грандиозный поток газа.',
        'description_en': 'Starburst galaxy. Superwind of gas erupts from the nucleus.',
    },
    {
        'id': 'm101', 'catalog_id': 'M101 / NGC 5457',
        'name': 'Pinwheel Galaxy', 'name_ru': 'Вертушка',
        'type': 'galaxy', 'type_ru': 'Спиральная галактика',
        'constellation': 'Ursa Major',
        'distance_ly': 21000000,
        'distance_note': '21 млн световых лет', 'distance_note_en': '21 million light-years',
        'magnitude': 7.86, 'ra': '14h 03m 13s', 'dec': '+54° 20′ 57″',
        'description_ru': 'Крупная спиральная галактика анфас. Диаметр — ~170 000 световых лет.',
        'description_en': 'Large face-on spiral galaxy. Diameter — ~170,000 light-years.',
    },
    {
        'id': 'm104', 'catalog_id': 'M104 / NGC 4594',
        'name': 'Sombrero Galaxy', 'name_ru': 'Сомбреро',
        'type': 'galaxy', 'type_ru': 'Линзообразная галактика',
        'constellation': 'Virgo',
        'distance_ly': 29000000,
        'distance_note': '29 млн световых лет', 'distance_note_en': '29 million light-years',
        'magnitude': 8.0, 'ra': '12h 39m 59s', 'dec': '−11° 37′ 23″',
        'description_ru': 'Узнаваемая галактика с тёмной пылевой полосой и большим балджем.',
        'description_en': 'Distinctive galaxy with dark dust lane and large central bulge.',
    },
    {
        'id': 'm64', 'catalog_id': 'M64 / NGC 4826',
        'name': 'Black Eye Galaxy', 'name_ru': 'Чёрный Глаз',
        'type': 'galaxy', 'type_ru': 'Спиральная галактика',
        'constellation': 'Coma Berenices',
        'distance_ly': 17000000,
        'distance_note': '17 млн световых лет', 'distance_note_en': '17 million light-years',
        'magnitude': 8.52, 'ra': '12h 56m 44s', 'dec': '+21° 40′ 59″',
        'description_ru': 'Получила название за тёмную полосу поглощающей пыли перед ярким ядром.',
        'description_en': 'Named for the dark absorbing dust band in front of its bright nucleus.',
    },
    {
        'id': 'milky_way_center', 'catalog_id': 'Sgr A*',
        'name': 'Milky Way Center (Sgr A*)', 'name_ru': 'Центр Млечного Пути (Sgr A*)',
        'type': 'galaxy', 'type_ru': 'Сверхмассивная чёрная дыра',
        'constellation': 'Sagittarius',
        'distance_ly': 26000,
        'distance_note': '26 000 световых лет', 'distance_note_en': '26,000 light-years',
        'magnitude': None, 'ra': '17h 45m 40s', 'dec': '−29° 00′ 28″',
        'description_ru': 'Сверхмассивная чёрная дыра в центре нашей Галактики. Масса — 4.15 млн масс Солнца. Сфотографирована в 2022 г.',
        'description_en': 'Supermassive black hole at the center of our Galaxy. Mass — 4.15 million solar masses. Photographed in 2022.',
    },
]

# Вспомогательный словарь: id → объект, для быстрого поиска по ссылке /catalog/<id>
CATALOG_BY_ID = {obj['id']: obj for obj in CATALOG}

# Все уникальные типы для фильтра
OBJECT_TYPES = sorted({obj['type'] for obj in CATALOG})
